parameters:
  - name: 'BASE_URL'
    displayName: 'target base url'
    type: string
    default: 'https://api.io.italia.it'
  - name: 'APIM_KEY'
    displayName: 'Api key'
    type: string

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: k6-load-test@0
    inputs:
      filename: 'src/submit_message.js'
