parameters:
  - name: 'BASE_URL'
    displayName: 'target base url'
    type: string
    default: 'https://api.io.italia.it'

pool:
  vmImage: 'ubuntu-latest'

steps:
  # - task: k6-load-test@0
  #   inputs:
  #     filename: 'src/submit_message.js'
  - script: |
      docker pull loadimpact/k6
    displayName: Pull k6 image
  - script: |
      docker run -i \
        -v `pwd`/src:/src \
        -e APIM_KEY=$(APIM_KEY) \
        -e BASE_URL=$(BASE_URL) \
        loadimpact/k6 \
        run /src/submit_message.js
    displayName: Run k6
